### PR TITLE
updated to 1.0, toolbar icon is gone, not in customize also

### PR DESCRIPTION
**Pull request by vsrawat**
Today I updated to fr 1.0, toolbar icon has gone missing, not finding in Customize also. (ff52 on w8)

Thanks.
-- 
Rawat

### CODE REVIEW

**Comment by Woundorf** [comment]
This should be an issue, not a pull request.

You can follow the steps explained in #213 and hopefully the icon should reappear. I'll copy the steps here for your convenience:

1. Restart Firefox
2. Uninstall and then install again FoxReplace (maybe with a Firefox restart in between to be sure)
3. As a last resort, use the "Restore defaults" button in the Customize menu

If you are lucky you won't need to do all the steps, only the first or the two firsts, but it's unpredictable.

**Comment by vsrawat** [comment]
uninstalled, restarted ff, reinstalled.

didn't work.

then, clicked restore defaults in customize area, and fr icon was back 
on the window, so moved that to toolbar.

solved. closed.

Thanks.
-- 
Rawat

**Comment by vsrawat** [comment]
something is surely broken here.

Only fr icon goes missing "every time I close firefox."

All other icons remain there.

I have added it many times again and again, by "reset" in customize, but 
it goes missing.

So, I guess something has gone wary.

I am on w8-32 bit with ff 52.0.2 but the same was working well with 
previous version. This behavior came as soon as upgraded to latest version.

Thanks.
-- 
Rawat

**Comment by Woundorf** [comment]
Several users have complained about this, but I can't reproduce the problem, so I can't fix it. The only thing that I have detected is that if I disable FoxReplace, open the menu, and then reenable FoxReplace, the button does not reappear, but it reappears after restart.

The thing that has changed is that now the button is added dynamically to Firefox, instead of being in a XUL overlay. But it is added just as explained by Mozilla, so it should be no problem, and indeed it's not a problem for several users, including myself.

The only thing that I can tell you is that in the next next version (i.e. two versions from now) it will be created in the WebExtension, and I hope that all these problems disappear.

**Comment by vsrawat** [comment]
I have now updated to ff 55.0.1, but the same problem of "fr icon missing from toolbar" remains.

I had manually added it through Customize - restore to default - drag drop, and it appeared, but when I closed and restarted ff, the fr icon wen missing again, whereas all other icons remained there.

Thanks.
-- 
Rawat

**Comment by Woundorf** [comment]
This also will hopefully be fixed in the soon to be approved version 1.1.2.

**Pull request closed without merging**
